"""fixed docs

Revision ID: 01604b872eb4
Revises: 76b651313271
Create Date: 2022-05-08 19:59:28.649865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01604b872eb4'
down_revision = '76b651313271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
