"""added tockens

Revision ID: 0959aabd3b47
Revises: 2098216f9bc1
Create Date: 2022-05-22 19:42:20.644301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0959aabd3b47'
down_revision = '2098216f9bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
