"""fixed docs

Revision ID: 1f84cd78281b
Revises: 26aa78e5a3f5
Create Date: 2022-05-08 20:14:40.266143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f84cd78281b'
down_revision = '26aa78e5a3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
