"""fixed docs

Revision ID: 26aa78e5a3f5
Revises: 01604b872eb4
Create Date: 2022-05-08 20:04:20.240481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26aa78e5a3f5'
down_revision = '01604b872eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
