"""fixed

Revision ID: 52527ecaafb2
Revises: 9f4d6f88c318
Create Date: 2022-05-14 00:07:59.756866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52527ecaafb2'
down_revision = '9f4d6f88c318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
