"""added invoices and listeners_agreements

Revision ID: 591d67bbcb71
Revises: 10b97f54e6b7
Create Date: 2022-05-09 07:42:01.183420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591d67bbcb71'
down_revision = '10b97f54e6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
