"""fixed all

Revision ID: 5e16a1d862b9
Revises: 3f43d4519679
Create Date: 2022-05-06 16:17:44.749751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e16a1d862b9'
down_revision = '3f43d4519679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
