"""fixed docs

Revision ID: 634358960e42
Revises: 98b074dca13c
Create Date: 2022-05-08 16:18:26.925623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634358960e42'
down_revision = '98b074dca13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
