"""added organizations

Revision ID: 64cb97a229a2
Revises: 951fab1e69f8
Create Date: 2022-05-16 14:44:22.801854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cb97a229a2'
down_revision = '951fab1e69f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
