"""added homeworks

Revision ID: 6b7a09c569f1
Revises: 2c27bb24bce7
Create Date: 2022-05-27 17:36:40.774795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7a09c569f1'
down_revision = '2c27bb24bce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listeners_homeworks', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('listeners_homeworks', 'check')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listeners_homeworks', sa.Column('check', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('listeners_homeworks', 'status')
    # ### end Alembic commands ###
