"""added homeworks

Revision ID: 7edfe5b04c33
Revises: 0959aabd3b47
Create Date: 2022-05-27 09:25:29.897271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edfe5b04c33'
down_revision = '0959aabd3b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
