"""fixed

Revision ID: 951fab1e69f8
Revises: 52527ecaafb2
Create Date: 2022-05-14 07:28:57.973455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951fab1e69f8'
down_revision = '52527ecaafb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
