"""fixed all

Revision ID: 98b074dca13c
Revises: 5e16a1d862b9
Create Date: 2022-05-06 16:44:23.362985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b074dca13c'
down_revision = '5e16a1d862b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
