"""fixed

Revision ID: 9f4d6f88c318
Revises: f2fa4da4c3c4
Create Date: 2022-05-14 00:03:32.426943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4d6f88c318'
down_revision = 'f2fa4da4c3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
