"""added partnership_agreements

Revision ID: a32cc5e853ba
Revises: b8cd33e78a76
Create Date: 2022-05-08 22:18:27.044601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32cc5e853ba'
down_revision = 'b8cd33e78a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnership_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('sale', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnership_agreements')
    # ### end Alembic commands ###
